services:
  postgres:
    image: postgres:17
    container_name: nestjslab_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: nestjslab
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5532:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: